apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - opensearch.yaml

patchesStrategicMerge:
  - retrieval-patch.yaml

# Remove the Redis VectorDB deployment
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: redis-vectordb
    namespace: opea-chatqna
  path: remove-redis.yaml