apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.9.0
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: bootstrap.memory_lock
          value: "true"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opea-chatqna
spec:
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
  type: ClusterIP