apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-service-account
  namespace: opea-chatqna
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bedrock-role
  namespace: opea-chatqna
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bedrock-role-binding
  namespace: opea-chatqna
subjects:
- kind: ServiceAccount
  name: bedrock-service-account
  namespace: opea-chatqna
roleRef:
  kind: Role
  name: bedrock-role
  apiGroup: rbac.authorization.k8s.io