apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: opea-chatqna
spec:
  template:
    spec:
      containers:
      - name: gateway
        env:
        - name: LLM_URL
          value: "http://llm-bedrock:8080"
        - name: LLM_TYPE
          value: "bedrock"