apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - bedrock-service-account.yaml
  - bedrock-llm.yaml

patchesStrategicMerge:
  - gateway-patch.yaml

# Remove the TGI LLM deployment
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: llm-tgi
    namespace: opea-chatqna
  path: remove-tgi.yaml