apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding
  template:
    metadata:
      labels:
        app: embedding
    spec:
      containers:
      - name: embedding
        image: quay.io/opea/chatqna-embedding:latest
        ports:
        - containerPort: 6000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: embedding
  namespace: opea-chatqna
spec:
  selector:
    app: embedding
  ports:
  - port: 6000
    targetPort: 6000
  type: ClusterIP