apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-tgi
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-tgi
  template:
    metadata:
      labels:
        app: llm-tgi
    spec:
      containers:
      - name: llm
        image: quay.io/opea/chatqna-tgi:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: llm-tgi
  namespace: opea-chatqna
spec:
  selector:
    app: llm-tgi
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP