apiVersion: apps/v1
kind: Deployment
metadata:
  name: reranker
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reranker
  template:
    metadata:
      labels:
        app: reranker
    spec:
      containers:
      - name: reranker
        image: quay.io/opea/chatqna-reranker:latest
        ports:
        - containerPort: 8008
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: reranker
  namespace: opea-chatqna
spec:
  selector:
    app: reranker
  ports:
  - port: 8008
    targetPort: 8008
  type: ClusterIP