apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-vectordb-pvc
  namespace: opea-chatqna
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: opea-chatqna
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi