apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: quay.io/opea/chatqna-ui:latest
        ports:
        - containerPort: 5173
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "150m"
            memory: "256Mi"
        env:
        - name: GATEWAY_URL
          value: "http://gateway:8888"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: opea-chatqna
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 5173
  type: LoadBalancer