apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-vectordb
  namespace: opea-chatqna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-vectordb
  template:
    metadata:
      labels:
        app: redis-vectordb
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:latest
        ports:
        - containerPort: 6379
        - containerPort: 8001
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-vectordb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-vectordb
  namespace: opea-chatqna
spec:
  selector:
    app: redis-vectordb
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: redisearch
    port: 8001
    targetPort: 8001
  type: ClusterIP