apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../guardrails/guardrails-configmap.yaml
  - ../opensearch/opensearch.yaml
  - ../bedrock/bedrock-service-account.yaml
  - ../bedrock/bedrock-llm.yaml

patchesStrategicMerge:
  - ../guardrails/gateway-patch.yaml
  - ../opensearch/retrieval-patch.yaml
  - ../bedrock/gateway-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: redis-vectordb
    namespace: opea-chatqna
  path: ../opensearch/remove-redis.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: llm-tgi
    namespace: opea-chatqna
  path: ../bedrock/remove-tgi.yaml