apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: opea-chatqna
spec:
  template:
    spec:
      containers:
      - name: gateway
        env:
        - name: GUARDRAILS_CONFIG_PATH
          value: "/etc/guardrails/guardrails.json"
        volumeMounts:
        - name: guardrails-config
          mountPath: /etc/guardrails/
      volumes:
      - name: guardrails-config
        configMap:
          name: guardrails-config